Link to `new_note_path`
This commit deviates from purely reactive, test-driven code changes.

The previous error was:

```
Error:
UserSharesAMessageTest#test_visiting_the_index:
Capybara::ElementNotFound: Unable to find field "Message"
    test/system/user_shares_a_message_test.rb:9:in `block in <class:UserSharesAMessageTest>'
```

The previous change to `click_on "Share a Note"` exercised an [`<a>`
element with an empty fragment (`href="#"`)][empty-fragment]. When
clicked, the browser does not navigate to a separate page.

If this change were motivated purely by test failures and error
messages, we'd need to add an element to the `notes#index` page with
`"Message"`.

However, since the call to `click_on "Share a Note"` didn't navigate to
a new page, introducing a change that navigates to a "new" page shortens
the path between our current behavior and our desired behavior.

Instead of rendering the text onto the current page, this commit
replaces the `<a href="#">...</a>` with a call to a [`link_to`
helper][link_to] that refers to (the currently undefined)
`new_note_path`.

The URL helper method is named `new_note_path` in order to route to the
`notes#new` action, in adherence to [Rails conventions][routing].

When the system tests are run, our test suite raises a new error:

```
Error:
UserSharesAMessageTest#test_visiting_the_index:
ActionView::Template::Error: undefined local variable or method `new_note_path' for #<#<Class:0x00007f88afceb3c0>:0x00007f88afcf3b60>
    app/views/notes/index.html.erb:1
```

[empty-fragment]: https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier
[link_to]: https://api.rubyonrails.org/v5.2/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to
[routing]: https://guides.rubyonrails.org/v5.2/routing.html#path-and-url-helpers